/**
 * Intent routing catalog (configuration only).
 *
 * Patterns are routing signals for the Intent Router — not ENARTE business rules
 * (prices, delivery SLAs, policies, etc. still belong in knowledge/business config).
 *
 * Engine reply templates are canned (no LLM). Override via env later if needed.
 */

/** Special decision intents (not workflow-bound). */
export const ROUTING_INTENT = Object.freeze({
  OUT_OF_DOMAIN: "out_of_domain",
  UNCLEAR: "unclear",
  GENERAL: "general",
  GREETING: "greeting",
  HELP: "help",
});

export const ROUTE_DECISION = Object.freeze({
  ROUTE: "route",
  CLARIFY: "clarify",
  OUT_OF_DOMAIN: "out_of_domain",
  GENERAL: "general",
});

/**
 * Maps detectable intents → target workflow ids.
 * Add a row here when a new workflow is registered.
 */
export const INTENT_DEFINITIONS = Object.freeze([
  {
    id: "greeting",
    workflowId: "general_chat",
    decision: ROUTE_DECISION.GENERAL,
    priority: 100,
    patterns: [
      "مرحبا",
      "مرحباً",
      "اهلا",
      "أهلا",
      "السلام",
      "hello",
      "hi",
      "hey",
      "good morning",
      "good evening",
    ],
  },
  {
    id: "help",
    workflowId: "general_chat",
    decision: ROUTE_DECISION.GENERAL,
    priority: 90,
    patterns: [
      "مساعدة",
      "ساعدني",
      "ماذا تستطيع",
      "ما هي خدماتكم",
      "help",
      "what can you do",
      "how can you help",
    ],
  },
  {
    id: "buy_chandelier",
    workflowId: "chandelier",
    decision: ROUTE_DECISION.ROUTE,
    priority: 86,
    patterns: [
      "ثريا",
      "ثريات",
      "نجفة",
      "chandelier",
      "chandeliers",
      "want a chandelier",
      "i want a chandelier",
      "looking for a chandelier",
      "buy a chandelier",
    ],
  },
  {
    id: "buy_fan",
    workflowId: "fan",
    decision: ROUTE_DECISION.ROUTE,
    priority: 85,
    patterns: [
      "مروحة",
      "مراوح",
      "fan",
      "fans",
      "ceiling fan",
      "want a fan",
      "i want a fan",
    ],
  },
  {
    id: "buy_outdoor",
    workflowId: "outdoor_lighting",
    decision: ROUTE_DECISION.ROUTE,
    priority: 84,
    patterns: [
      "إضاءة خارجية",
      "اضاءة خارجية",
      "outdoor",
      "outdoor lighting",
      "garden light",
      "want outdoor",
    ],
  },
  {
    id: "site_inspection",
    workflowId: "site_inspection",
    decision: ROUTE_DECISION.ROUTE,
    priority: 67,
    patterns: [
      "معاينة",
      "معاينة الموقع",
      "زيارة موقع",
      "site inspection",
      "site visit",
      "inspect the site",
      "يكشف",
      "كشف",
      "تمروا",
      "تمرو",
      "تجوني",
      "تجوا",
      "يمرلي",
      "يمر لي",
      "موعد معاينة",
      "حجز موعد",
      "مرّوا لعندي",
      "مرو لعندي",
      "عندي كشف",
    ],
  },
  {
    id: "product_search",
    workflowId: "product_search",
    decision: ROUTE_DECISION.ROUTE,
    priority: 80,
    patterns: [
      "بحث",
      "ابحث",
      "أبحث",
      "منتج",
      "إضاءة",
      "اضاءة",
      "product",
      "find",
      "search",
      "looking for",
      "pendant",
      "lamp",
      "bulb",
      "bulbs",
      "light bulb",
      "light bulbs",
      "لمبة",
      "لمبات",
      "بلب",
      "بلبات",
      "اضوية",
      "إنارة",
      "انارة",
    ],
  },
  {
    id: "shopify_search",
    workflowId: "shopify_product_search",
    decision: ROUTE_DECISION.ROUTE,
    priority: 78,
    patterns: ["shopify", "المتجر", "store catalog", "catalog"],
  },
  {
    id: "recommend_products",
    workflowId: "product_recommendations",
    decision: ROUTE_DECISION.ROUTE,
    priority: 76,
    patterns: [
      "اقترح",
      "اقترحوا",
      "توصية",
      "توصيات",
      "suggest",
      "recommend",
      "recommendation",
      "what do you recommend",
    ],
  },
  {
    id: "search_by_image",
    workflowId: "image_search",
    decision: ROUTE_DECISION.ROUTE,
    priority: 74,
    patterns: [
      "بحث بالصورة",
      "صورة منتج",
      "image search",
      "search by image",
      "photo of product",
      "similar to this image",
    ],
  },
  {
    id: "analyze_room",
    workflowId: "room_analysis",
    decision: ROUTE_DECISION.ROUTE,
    priority: 72,
    patterns: [
      "تحليل الغرفة",
      "حلل الغرفة",
      "صورة الغرفة",
      "غرفتي",
      "analyze room",
      "room analysis",
      "room photo",
      "my room",
    ],
  },
  {
    id: "place_chandelier",
    workflowId: "virtual_placement",
    decision: ROUTE_DECISION.ROUTE,
    priority: 70,
    patterns: [
      "تجربة",
      "ضع الثريا",
      "تركيب افتراضي",
      "في الغرفة",
      "try in room",
      "virtual placement",
      "place chandelier",
      "place in room",
    ],
  },
  {
    id: "delivery",
    workflowId: "delivery",
    decision: ROUTE_DECISION.ROUTE,
    priority: 68,
    patterns: [
      "توصيل",
      "الشحن",
      "متى يصل",
      "التوصيل",
      "delivery",
      "shipping",
      "when will it arrive",
      "ship",
    ],
  },
  {
    id: "returns",
    workflowId: "returns",
    decision: ROUTE_DECISION.ROUTE,
    // Above product_search so "إرجاع المنتج" is not treated as a catalog search.
    priority: 85,
    patterns: [
      "ارجاع",
      "إرجاع",
      "ترجيع",
      "استبدال",
      "تبديل",
      "ارجاع المنتج",
      "إرجاع المنتج",
      "ترجيع المنتج",
      "استبدال المنتج",
      "تبديل المنتج",
      "بدي ارجع",
      "بدي أرجع",
      "ابغى ارجع",
      "سياسة الارجاع",
      "سياسة الإرجاع",
      "سياسة الاستبدال",
      "return",
      "returns",
      "exchange",
      "refund",
      "can i return",
      "can i exchange",
      "want to return",
      "want to exchange",
    ],
  },
  {
    id: "installation",
    workflowId: "installation",
    decision: ROUTE_DECISION.ROUTE,
    priority: 66,
    patterns: [
      "تركيب",
      "التثبيت",
      "تركيب الثريا",
      "كهربجي",
      "كهربائي",
      "electrician",
      "فني تركيب",
      "فني كهربا",
      "فني",
      "installation",
      "install",
      "mounting",
      "how to install",
      "كيف أركبها",
      "كيف اركبها",
      "كيف ركبها",
      "مين يركبها",
      "مين بدو يركبها",
      "مين بيركب",
      "أنتم بتركبو",
      "انتو بتركبو",
      "بتتركبو",
      "عندكم فني",
      "عندكم كهربجي",
      "فريق تركيب",
      "شورت",
      "شرارة",
      "فيوز",
      "short circuit",
      "electrical short",
    ],
  },
  {
    id: "maintenance",
    workflowId: "maintenance",
    decision: ROUTE_DECISION.ROUTE,
    priority: 64,
    patterns: [
      "صيانة",
      "تنظيف",
      "العناية",
      "maintenance",
      "care",
      "clean",
      "how to clean",
    ],
  },
  {
    id: "custom_chandelier",
    workflowId: "custom_chandeliers",
    decision: ROUTE_DECISION.ROUTE,
    priority: 62,
    patterns: [
      "تفصيل",
      "حسب الطلب",
      "مخصص",
      "custom",
      "bespoke",
      "custom chandelier",
      "made to order",
    ],
  },
  {
    id: "sourcing",
    workflowId: "product_sourcing",
    decision: ROUTE_DECISION.ROUTE,
    priority: 60,
    patterns: [
      "توريد",
      "استيراد",
      "sourcing",
      "source product",
      "procure",
      "supplier",
    ],
  },
  {
    id: "suggestions_feedback",
    workflowId: "suggestions_feedback",
    decision: ROUTE_DECISION.ROUTE,
    priority: 58,
    patterns: [
      "اقتراح",
      "ملاحظات",
      "شكوى",
      "feedback",
      "suggestion",
      "complaint",
      "review",
    ],
  },
  {
    id: "notify_admin",
    workflowId: "admin_notifications",
    decision: ROUTE_DECISION.ROUTE,
    priority: 50,
    patterns: ["بلغ الإدارة", "notify admin", "contact admin"],
  },
]);

/** Clearly off-domain routing signals (not business policy). */
export const OUT_OF_DOMAIN_PATTERNS = Object.freeze([
  "weather",
  "الطقس",
  "طقس",
  "recipe",
  "وصفة",
  "طبخ",
  "طبخة",
  "football",
  "كرة القدم",
  "كرة",
  "مباراة",
  "رياضة",
  "sports",
  "crypto",
  "bitcoin",
  "بيتكوين",
  "programming",
  "برمجة",
  "كود",
  "javascript",
  "python",
  "homework",
  "واجب",
  "دراسة",
  "politics",
  "سياسة",
  "انتخابات",
  "stock market",
  "أسهم",
  "بورصة",
  "joke",
  "نكتة",
  "نكت",
  "movie",
  "فيلم",
  "مسلسل",
  "music",
  "أغنية",
  "music",
  "religion",
  "دين",
  "فتوى",
  "medical",
  "دواء",
  "طبيب",
  "مستشفى",
  "travel",
  "سفر",
  "طيارة",
  "حجز فندق",
  "who is",
  "من هو",
  "ما هو معنى",
  "chatgpt",
  "اكتب لي قصة",
  "قصيدة",
  "شعر",
]);

/**
 * Canned engine replies (locale → text). Not LLM output.
 * Domain specialization copy lives in config so workflows stay logic-free.
 */
export const ENGINE_REPLY_TEMPLATES = Object.freeze({
  out_of_domain: Object.freeze({
    ar: "لا أستطيع التحدث خارج سياق المتجر. هل تريد المساعدة في اختيار إنارة معينة أو شيء آخر من اختصاصي؟",
    en: "I cannot talk outside this store's context. Would you like help choosing specific lighting or something else in my specialty?",
  }),
  clarify: Object.freeze({
    ar: "للتأكد أنني أساعدك بشكل صحيح: ماذا تبحث عنه في إضاءة ENARTE؟",
    en: "Just to guide you correctly: what are you looking for in ENARTE lighting?",
  }),
  greeting: Object.freeze({
    ar: "أهلاً بك — أنا مستشار إضاءة ENARTE. صف احتياجك أو ابدأ من الأزرار، وأرشدك لأفضل خيار في الكتالوج.",
    en: "Welcome — I'm your ENARTE lighting consultant. Tell me what you need (or use a button), and I'll guide you to the best catalog match.",
  }),
  help: Object.freeze({
    ar: "خلّيني أساعدك كمستشار مبيعات: منتجات، إضاءة، توصيل، تركيب — اسأل مباشرة.",
    en: "Ask me anything about ENARTE products, lighting, delivery, or installation — I'll guide you like a sales consultant.",
  }),
});

export const INTENT_ROUTER_SETTINGS = Object.freeze({
  /** Minimum score to accept a domain intent without clarification. */
  minRouteScore: 1,
  /** If top two domain scores are within this margin, ask one clarifying question. */
  ambiguityMargin: 0,
  /** Prefer out-of-domain when its score is at least this and no stronger domain hit. */
  outOfDomainMinScore: 1,
});

export function resolveReplyTemplate(templates, key, locale = "ar") {
  const pack = templates?.[key];
  if (!pack) return "";
  const normalized = String(locale || "ar").toLowerCase().startsWith("en")
    ? "en"
    : "ar";
  return pack[normalized] || pack.ar || pack.en || "";
}

export function loadIntentCatalog() {
  return Object.freeze({
    intents: INTENT_DEFINITIONS,
    outOfDomainPatterns: OUT_OF_DOMAIN_PATTERNS,
    replies: ENGINE_REPLY_TEMPLATES,
    settings: INTENT_ROUTER_SETTINGS,
  });
}
